In [79]:
import pandas as pd
import numpy as np
df = pd.read_csv("animes.csv")
import matplotlib.pyplot as plt
import scipy
import re
# Remove duplicates
df = df.drop_duplicates()
# changing columns types from string to int
df['members'] = df['members'].astype(int)
df['popularity'] = df['popularity'].astype(int)
# changing string back into string array with each genre being its own element in array
df['genre'] = df['genre'].apply(eval)
#dropping the image url and link from table since it won't be needed
df = df.drop('img_url', axis=1)
df = df.drop('link', axis=1)
# converting string into two dates and only getting the first date
df['aired'] = df['aired'].str.split(' to ').str[0]
#function that will format the string into a datetime object to be comparable, also adds in missing data if missing month and or day.
def parse_date(date_str):
    formats = [r'^\w+ \d+\, \d{4}$', r'^\w+ \d{4}$', r'^\d{4}$']
    for fmt in formats:
      x = re.search(fmt, date_str)
      if (x):
        x = str(x.group())
        if fmt == r'^\w+ \d{4}$':
          x = x.replace(" ", " 1, ")
        elif fmt == r'^\d{4}$':
          x = "January 1, "+ x
      return pd.to_datetime(x)
    return pd.NaT
df['aired'] = df['aired'].apply(parse_date).dt.year
df['synopsis'] = df['synopsis'].fillna(' ')
df = df.dropna()
display(df)
df.to_csv('d2.csv')
# df_genres = df.explode('genre')
# genre_counts = df_genres['genre'].value_counts()
# df = df.dropna()
# display(genre_counts)
# display(len(df_genres['genre']))
# unique_genres = df_genres['genre'].unique()

# # Create new genre columns with 0s
# for genre in unique_genres:
#   df[genre] = 0

# # Fill 1s for matching genres in each row
# for index, row in df_genres.iterrows():
#   df.loc[index, row['genre']] = 1

# # Drop the original 'genre' column (optional)
# print(df)
# df.dropna()
# df = df.loc[:, (df.columns.astype(str) != 'nan') & (df.columns.notna()) & (df.columns.str.isalnum())]
# df = df.dropna()

,uid,title,synopsis,genre,aired,episodes,members,popularity,ranked,score
0,28891,Haikyuu!! Second Season,Following their participation at the Inter-Hig...,"[Comedy, Sports, Drama, School, Shounen]",2015.0,25.0,489888,141,25.0,8.82
1,23273,Shigatsu wa Kimi no Uso,Music accompanies the path of the human metron...,"[Drama, Music, Romance, School, Shounen]",2014.0,22.0,995473,28,24.0,8.83
2,34599,Made in Abyss,The Abyss—a gaping chasm stretching down into ...,"[Sci-Fi, Adventure, Mystery, Drama, Fantasy]",2017.0,13.0,581663,98,23.0,8.83
3,5114,Fullmetal Alchemist: Brotherhood,"""In order for something to be obtained, someth...","[Action, Military, Adventure, Comedy, Drama, M...",2009.0,64.0,1615084,4,1.0,9.23
4,31758,Kizumonogatari III: Reiketsu-hen,After helping revive the legendary vampire Kis...,"[Action, Mystery, Supernatural, Vampire]",2017.0,1.0,214621,502,22.0,8.83
...,...,...,...,...,...,...,...,...,...,...
19002,10075,Naruto x UT,All-new animation offered throughout UNIQLO cl...,"[Action, Comedy, Super Power, Martial Arts, Sh...",2011.0,1.0,34155,2382,1728.0,7.50
19003,35828,Miira no Kaikata,High school student Sora Kashiwagi is accustom...,"[Slice of Life, Comedy, Supernatural]",2018.0,12.0,61459,1648,1727.0,7.50
19004,10378,Shinryaku!? Ika Musume,"After regaining her squid-like abilities, Ika ...","[Slice of Life, Comedy, Shounen]",2011.0,12.0,67422,1547,1548.0,7.56
19005,33082,Kingsglaive: Final Fantasy XV,"For years, the Niflheim Empire and the kingdom...",[Action],2016.0,1.0,41077,2154,1544.0,7.56
19006,16934,Chuunibyou demo Koi ga Shitai!: Kirameki no......,Although Yuuta Togashi and Rikka Takanashi hav...,"[Comedy, Drama, Romance, School, Slice of Life]",2013.0,1.0,128400,883,1533.0,7.56

In [74]:
def remove_non_str_nan(df):
  """
  Removes columns from a DataFrame where the column title is not a string or is NaN.

  Args:
      df (pandas.DataFrame): The DataFrame to filter.

  Returns:
      pandas.DataFrame: The DataFrame with filtered columns.
  """
  return df.loc[:, (df.columns.astype(str) != 'nan') & (df.columns.notna()) & (df.columns.str.isalnum())]

filtered_df = remove_non_str_nan(df.copy())
print(filtered_df)

                                  title  \
0               Haikyuu!! Second Season
1               Shigatsu wa Kimi no Uso
2                         Made in Abyss
3      Fullmetal Alchemist: Brotherhood
4      Kizumonogatari III: Reiketsu-hen
...                                 ...
18888                               NaN
18934                               NaN
18972                               NaN
19251                               NaN
19266                               NaN

                                                   genre  episodes  \
0               [Comedy, Sports, Drama, School, Shounen]      25.0
1               [Drama, Music, Romance, School, Shounen]      22.0
2           [Sci-Fi, Adventure, Mystery, Drama, Fantasy]      13.0
3      [Action, Military, Adventure, Comedy, Drama, M...      64.0
4               [Action, Mystery, Supernatural, Vampire]       1.0
...                                                  ...       ...
18888                                                NaN       NaN
18934                                                NaN       NaN
18972                                                NaN       NaN
19251                                                NaN       NaN
19266                                                NaN       NaN

       popularity  ranked  score  Comedy  Sports  Drama  School  ...  Shoujo  \
0           141.0    25.0   8.82     1.0     1.0    1.0     1.0  ...     0.0
1            28.0    24.0   8.83     0.0     0.0    1.0     1.0  ...     0.0
2            98.0    23.0   8.83     0.0     0.0    1.0     0.0  ...     0.0
3             4.0     1.0   9.23     1.0     0.0    1.0     0.0  ...     0.0
4           502.0    22.0   8.83     0.0     0.0    0.0     0.0  ...     0.0
...           ...     ...    ...     ...     ...    ...     ...  ...     ...
18888         NaN     NaN    NaN     1.0     NaN    NaN     NaN  ...     NaN
18934         NaN     NaN    NaN     NaN     NaN    NaN     NaN  ...     NaN
18972         NaN     NaN    NaN     1.0     NaN    NaN     NaN  ...     NaN
19251         NaN     NaN    NaN     NaN     NaN    NaN     NaN  ...     NaN
19266         NaN     NaN    NaN     1.0     NaN    NaN     1.0  ...     NaN

       Horror  Cars  Game  Thriller  Dementia  Harem  Hentai  Yaoi  Yuri
0         0.0   0.0   0.0       0.0       0.0    0.0     0.0   0.0   0.0
1         0.0   0.0   0.0       0.0       0.0    0.0     0.0   0.0   0.0
2         0.0   0.0   0.0       0.0       0.0    0.0     0.0   0.0   0.0
3         0.0   0.0   0.0       0.0       0.0    0.0     0.0   0.0   0.0
4         0.0   0.0   0.0       0.0       0.0    0.0     0.0   0.0   0.0
...       ...   ...   ...       ...       ...    ...     ...   ...   ...
18888     NaN   NaN   NaN       NaN       NaN    NaN     NaN   NaN   NaN
18934     NaN   NaN   NaN       NaN       NaN    NaN     NaN   NaN   NaN
18972     NaN   NaN   NaN       NaN       NaN    NaN     NaN   NaN   NaN
19251     NaN   NaN   NaN       NaN       NaN    NaN     NaN   NaN   NaN
19266     NaN   NaN   NaN       NaN       NaN    NaN     NaN   NaN   NaN

[19311 rows x 43 columns]